more windows build fixes...Not sure how to fix the errors for this: 1>g:\devenv\ve-suite_1.1\share\tools\aspen\ve_aspenunit\bkpparser.cpp(1153) : error C2440: 'initializing' : cannot convert from 'VE_XML::DataValuePairWeakPtr' to 'VE_XML::DataValuePair *'